# infrastructure/configs/secret.yaml
apiVersion: v1
kind: Secret
metadata:
  name: secret-value
  namespace: netflow
type: Opaque
stringData:
  MONGO_USERNAME: "admin"
  MONGO_PASSWORD: "mongo"
  MONGO_URI: "mongodb://admin:mongo@mongo-svc:27017"

  RABBITMQ_DEFAULT_USER: "guest"
  RABBITMQ_DEFAULT_PASS: "guest"

